name: StructureLoader
main: StructureLoader\Loader
version: 1.0
api: [2.0.0, 3.0.1, 3.0.0]
author: Liuviy
 
commands:
  ".load":
    default: op
    description: "Loading a structure from StructureData file."